version: "3"

services:
  db:
    image:  mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      db-data: /var/lib/mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Test1234'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Test9876'
    expose: 
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports: 
      - 80:80
    restart: always
    enviroment:
      WORDPRESS_DB_HOST: 'db'
      WORDPRESS_DB_USER: 'admin'
      WORDPRESS_DB_PASSWORD: 'Test9876'
      WORDPRESS_DB_NAME: 'wordpress'
  volumes: 
    db_data: